---
## add a stack and set permissions
- name: add stack
  uri:
    url: "http://{{codeready_url}}/api/stack"
    method: POST
    body: "{{ stack_json }}"
    status_code: 201
    body_format: json
    headers:
      Authorization: "Bearer {{ codeready_access_token_bearer }}"
  register: stack_json_result

- set_fact:
    stack_id: "{{ stack_json_result.json|json_query('id') }}"

- name: give all users access to the stack
  uri:
    url: "http://{{ codeready_url }}/api/permissions"
    method: POST
    body: "{{ lookup('template','stack-permissions.json.j2', convert_data=False) }}"
    status_code: 204
    body_format: json
    headers:
      Authorization: "Bearer {{ codeready_access_token_bearer }}"
  vars:
    stack_id: "{{ stack_id }}"