---
- name: get CodeReady Workspaces APB from GitHub
  git:
    repo: https://github.com/redhat-developer/codeready-workspaces-apb.git
    dest: codeready-workspaces-apb
    version: operator
  tags: codeready-workspaces
- name: Deploy CodeReady Workspaces
  command: "./deploy.sh --deploy"
  register: res_cmd
  changed_when: res_cmd.rc == 0
  args:
    chdir: codeready-workspaces-apb/apb/
  tags: codeready-workspaces
