---
- name: get CodeReady Workspaces APB from GitHub
  git:
    repo: https://github.com/redhat-developer/codeready-workspaces-apb.git
    dest: codeready-workspaces-apb
    version: operator
    force: yes
  tags: codeready-workspaces
- name: Delete codeready project if existed
  command: "oc delete project codeready"
  register: res_cmd
  changed_when: res_cmd.rc == 0
  ignore_errors: true
  tags: codeready-workspaces
- name: Create codeready project
  command: "oc new-project codeready"
  register: res_cmd
  changed_when: res_cmd.rc == 0
  ignore_errors: true
  tags: codeready-workspaces
- name: delete codeready project quota
  command: "oc delete limitrange --all"
  register: res_cmd
  changed_when: res_cmd.rc == 0
  tags: codeready-workspaces
- name: Deploy CodeReady Workspaces
  command: "./deploy.sh --deploy"
  register: res_cmd
  changed_when: res_cmd.rc == 0
  args:
    chdir: codeready-workspaces-apb/apb/
  tags: codeready-workspaces
- name: Disable RHSSO ssl_required for requests for realms/master
  command: "oc rsh deployment/keycloak /opt/eap/bin/kcadm.sh update realms/master -s sslRequired=none"
  register: res_cmd
  changed_when: res_cmd.rc == 0
  ignore_errors: true
  tags: codeready-workspaces
- name: Disable RHSSO ssl_required for requests for realms/codeready
  command: "oc rsh deployment/keycloak /opt/eap/bin/kcadm.sh update realms/codeready -s sslRequired=none"
  register: res_cmd
  changed_when: res_cmd.rc == 0
  ignore_errors: true
  tags: codeready-workspaces
